version: "3.9"

services:
  validator-node:
    image: fluxprotocol/oracle-validator-node
    container_name: flux-validator-node
    profiles: ["light-node", "full-node"]
    build:
      context: .
      dockerfile: docker/Dockerfile.validator-node
    volumes:
      - .:/validator-node
    ports:
      - "3000:3000"

  near-node:
    image: nearprotocol/nearup
    container_name: nearup
    profiles: ["full-node"]
    command: "run ${NETWORK}"
    volumes:
      - .near:/root/.near
    ports:
      - "3030:3030"
