version: "3.9"

services:
  validator-node:
    image: fluxprotocol/oracle-validator-node
    container_name: flux-validator-node
    build:
      context: .
      dockerfile: docker/Dockerfile.validator-node
    volumes:
      - .:/validator-node
    ports:
      - "3000:3000"
