version: "3.9"

services:
  validator-node:
    image: fluxprotocol/oracle-validator-node
    container_name: flux-validator-node
    profiles: ["light-node", "full-node"]
    build:
      context: .
      dockerfile: docker/Dockerfile.validator-node
    volumes:
      - .:/validator-node
    ports:
      - "3000:3000"

  near-node:
    image: nearprotocol/nearup
    container_name: nearup
    profiles: ["full-node"]
    command: "run ${NETWORK}"
    volumes:
      - nearup_container:/root/.near
    ports:
      - "3030:3030"

  mongodb:
    image: mongo:latest
    container_name: flux-oracle-explorer-mongodb
    profiles: ["explorer", "full-node"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  explorer-api:
    image: fluxprotocol/oracle-explorer-api
    container_name: flux-oracle-explorer-api
    profiles: ["explorer", "full-node"]
    build:
      context: ./docker
      dockerfile: ./Dockerfile.explorer-api
    environment:
      APP_PORT: 4000
      PROTOCOL_ACCOUNT: ${ORACLE_CONTRACT}
    ports:
      - 4000:4000
    depends_on:
      - "mongodb"
    volumes:
      - .:/explorer-api

  explorer-fe:
    image: fluxprotocol/oracle-explorer-fe
    container_name: flux-oracle-explorer-fe
    profiles: ["explorer", "full-node"]
    build:
      context: ./docker
      dockerfile: ./Dockerfile.explorer-fe
    environment:
      REACT_APP_NEAR_NETWORK: ${NETWORK}
      REACT_APP_NEAR_ORACLE_CONTRACT_ID: ${ORACLE_CONTRACT}
      REACT_APP_NEAR_FLUX_TOKEN_ID: ${FLUX_TOKEN_CONTRACT}
      REACT_APP_NEAR_NULL_CONTRACT: ${NULL_CONTRACT}
      REACT_APP_COINGECKO_API_URL: ${COINGECKO_API_URL}
    ports:
      - 3000:3000
    depends_on:
      - "explorer-api"
    volumes:
      - .:/explorer-fe

volumes:
  mongodb_data_container:
  nearup_container:
